name: Generate Snake Game Animation

on:
  schedule:
    - cron: '0 0 * * *' # Run at midnight UTC every day
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate GitHub Contribution Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # Automatically uses the repository owner's username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Outputs are pushed to the 'output' branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Uses GitHub token from secrets for authentication
